In [ ]:
def somaMatriz(m1, m2):
    if len(m1) != len(m2) or len(m1[0]) != len(m2[0]) or len(m1) != len(m1[0]):
        print("As matrizes devem ter as mesmas dimensões!")
        return none
    n = len(m1)
    resultado = [[0] *n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            resultado [i][j] = m1[i][j]+m2[i][j]
    return resultado
m1 = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
m2 = [[9, 8, 7],
      [6, 5, 4],
      [3, 2, 1]]
resultado = somaMatriz(m1, m2)
if resultado:
    print("A soma das matrizes é: ")
    for linha in resultado:
        print(linha)

In [ ]:
def somaMatriz(m1, m2):
    if len(m1) != len(m2) or len(m1[0]) != len(m2[0]) or len(m1) != len(m1[0]):
        print("As matrizes devem ter as mesmas dimensões!")
        return none
    n = len(m1)
    resultado = [[0] *n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            resultado [i][j] = m1[i][j]+m2[i][j]
    return resultado
m1 = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
m2 = [[9, 8, 7],
      [6, 5, 4],
      [3, 2, 1]]
resultado = somaMatriz(m1, m2)
if resultado:
    print("A soma das matrizes é: ")
    for linha in resultado:
        print(linha)

In [3]:
import numpy as np
def somaMatrizes(matriz1, matriz2):
    if matriz1.shape != matriz2.shape:
        print("As matrizes devem ter as mesmas dimensões!")
        return None
    resultado = matriz1+matriz2
    return resultado
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9 ]])
matriz2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1 ]])
resultado = somaMatrizes(matriz1, matriz2)
if resultado is not None:
    print("A soma das matrizes é: ")
    print(resultado)

A soma das matrizes é: 
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [2]:
import numpy as np
def menosMatriz(m1, m2):
    if m1.shape != m2.shape:
        print("As matrizes devem ter as mesmas dimensões! ")
        return None
    resultado = m1-m2
    return resultado
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
resultado = menosMatriz(m1, m2)
if resultado is not None:
    print("A subtração das matrizes é: ")
    for linha in resultado:
        print(linha)

A subtração das matrizes é: 
[-8 -6 -4]
[-2  0  2]
[4 6 8]


In [12]:
import numpy as np
def calculaTransposta(m):
    resultado = m.transpose()
    return resultado
m = np.array([[1, 2, 3], [4, 5, 6]])
resultado = calculaTransposta(m)
if resultado is not None:
    print("A matriz transposta à original é: ")
    for linha in resultado:
        print(linha)

A matriz transposta à original é: 
[1 4]
[2 5]
[3 6]


In [1]:
import numpy as np
def multiplicaMatriz(a, b):
    resultado = np.dot(a, b)
    return resultado
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
resultado = multiplicaMatriz(a, b)
print("O resultado da multiplicação dessas duas matrizes é: ")
for linha in resultado:
    print(linha)

O resultado da multiplicação dessas duas matrizes é: 
[19 22]
[43 50]


In [2]:
import numpy as np
def naoNulo(m):
    resultado = print("Temos " +str(desanulado) + "posições não nulas nessa matriz")
    return resultado
m = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [0, 2, 4, 6, 8, 10, 12, 14, 16, 18], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [4, 4, 4, 4, 4, 4, 4, 4, 4, 4], [1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [0, -2, -4, -6, -8, -10, -12, -14, -16, -18], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [10, 10, 10, 10, 10, 10, 10, 10, 10, 10], [-1, -3, -5, -7, -9, -11, -13, -15, -17, -19]])
desanulado=0
for i in range(len(m)):
    for j in range(len(m[i])):
        if (m[i][j]) != 0:
            desanulado+=1
resultado = naoNulo(m)

Temos 88posições não nulas nessa matriz


In [ ]:
def main():
    num_corredores = 6
    num_voltas = 10
    tempos = []
    nomes = []
    for i in range(num_corredores):
        nome = input(f"Digite o nome do corredor {i+1}: ")
        nomes.append(nome)
        voltas = []
        for j in range(num_voltas):
            tempo = float(input(f"Digite o tempo da volta {j+1} para o corredor {nome} (em segundos): "))
            voltas.append(tempo)
        tempos.append(voltas)
    melhor_tempo

In [5]:
import numpy as np
m = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
for linha in m:
    print(linha)

[1 1 1]
[2 2 2]
[3 3 3]
